#!/usr/bin/env python3
# https://github.com/pengux/dotfiles/blob/pn/wayland/.config/sway/random_bg
import glob
import random
import sys
from os.path import expanduser

homeDir = expanduser("~")
args = sys.argv[1:]
if len(args) == 0:
    args = [""]
walls = list()
for source in args:
    walls += glob.glob(f"{homeDir}/Pictures/Wallpapers/" + source + "/*.*")
print(random.choice(walls))
